### ISSUE TITLE
Will this library support latest allennlp?

### ISSUE THREAD

**Issue by thak123** [machamp-nlp/machamp#10]
# Questions
Hi 
cool work and kudos for putting up something like this.
just a quick question. Is this library supported by the latest Allennlp and what will be the future enhancements we can expect ?

**Comment by robvanderg** [comment]
Hi Thak123, 

I am planning to update to a newer Allennlp version, but this will not be soon, as I am on a partial leave. Soonest would be end of this year. 

The features of MaChAmp are purely based on our research agenda, which means we mostly implement features that can answer our research questions. This is also the reason we keep them in private repo's, so that our research papers can be submitted anonymously. If you have any feature you would like to see, or even a "feature-direction", you can always open an issue, or contact me via e-mail or on the MaChAmp slack channel: https://join.slack.com/t/machamp-workspace/shared_invite/zt-piuoliwh-KaGJUwanucKKprx9IObJ6A (maybe we are already working on it)

**Comment by thak123** [comment]
@robvanderg thanks for the reply.
